name: 'Generate Localization'

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  generate:
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout this repository'
        uses: actions/checkout@v7
      - name: 'Checkout d2-localization-generator'
        uses: actions/checkout@v7
        with:
          repository: 'Taskeren/d2-localization-generator'
          path: 'i18n-generator'
      - name: 'Setup nodejs'
        uses: actions/setup-node@v6.4.0
        with:
          node-version: '24'
      - name: 'Run generator'
        run: |
          cd i18n-generator || exit 1
          npm install
          npm run run
        env:
          BUNGIE_API_KEY: '${{ secrets.BUNGIE_API_TOKEN }}'
      - name: 'Copy generated'
        run: |
          mkdir -p ./src/generated/
          cp -r i18n-generator/out/* ./src/generated/
      - name: 'Remove d2-localization-generator'
        run: rm -rf i18n-generator
      - name: 'Get date information'
        id: date
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: 'Open pull request'
        uses: peter-evans/create-pull-request@v8.1.1
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          branch: 'bot/i18n'
          commit-message: '[i18n] regenerate localization data ${{ env.CURRENT_DATE }}'
          title: '[I18N] Localization Update ${{ env.CURRENT_DATE }}'
          reviewers: 'Taskeren'
          labels: i18n
          delete-branch: true
